### ISSUE TITLE
I can't find authenticate function

### ISSUE THREAD

**Issue by wanyoung1231** [spira/angular-jwt-auth#28]
![b2377b13-700c-4c38-9264-8f024a7dadf4](https://cloud.githubusercontent.com/assets/3946765/9197991/5e9d10b6-406b-11e5-80f2-9e627618f5d1.png)

Is a document written wrong?

**Comment by zakhenry** [comment]
There is no file uploaded?

**Comment by wanyoung1231** [comment]
I have modified the comments

**Comment by zakhenry** [comment]
Okay I realised that I have changed the api and forgot to update the readme. It is patched now. The correct method is `authenticateCredentials`. Thanks for the pickup
